//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Beblang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BeblangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBeblangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] BeblangParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] BeblangParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.moduleStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleStatements([NotNull] BeblangParser.ModuleStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.moduleImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleImport([NotNull] BeblangParser.ModuleImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.subprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram([NotNull] BeblangParser.SubprogramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.subprogramDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogramDeclaration([NotNull] BeblangParser.SubprogramDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] BeblangParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.variableDeclarationBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarationBlock([NotNull] BeblangParser.VariableDeclarationBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.subprogramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogramBody([NotNull] BeblangParser.SubprogramBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] BeblangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] BeblangParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.subprogramCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogramCall([NotNull] BeblangParser.SubprogramCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] BeblangParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.exitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitStatement([NotNull] BeblangParser.ExitStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] BeblangParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStatement([NotNull] BeblangParser.ElseIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] BeblangParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] BeblangParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] BeblangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleExpression([NotNull] BeblangParser.SimpleExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] BeblangParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] BeblangParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignator([NotNull] BeblangParser.DesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] BeblangParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdentifier([NotNull] BeblangParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] BeblangParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] BeblangParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BeblangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] BeblangParser.TypeContext context);
}
